#! /bin/sh

sxhkd &

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config focus_follows_pointer true 

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a URxvt:quake sticky=on follow=on
bspc rule -a Gimp desktop=^8 floating=on follow=on
bspc rule -a google-chrome desktop=^1
bspc rule -a google-chrome:crx_hmjkmjkepdijhoojdojkdfohbdgmmhki state=floating sticky=on follow=on
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
