taskkill /f /im AutoHotkey.exe
taskkill /f /im googledrivesync.exe
taskkill /f /im Evernote.exe
taskkill /f /im EvernoteTray.exe
taskkill /f /im flux.exe
taskkill /f /im MusicBee.exe
taskkill /f /im zotero.exe
taskkill /f /im chrome.exe
taskkill /f /im SumatraPDF.exe
taskkill /f /im Xming.exe
taskkill /f /im bash.exe
taskkill /f /im calibre.exe